name: sync-translate
on:
  push:
    branches:
      - master
    paths:
      - '**.csv'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Get Commit Info
        id: get-commit-info
        run: |
          COMMIT_EMAIL=$(git log -1 --pretty=format:'%ae')
          COMMIT_USERNAME=$(git log -1 --pretty=format:'%an')
          echo "COMMIT_EMAIL=$(git log -1 --pretty=format:'%ae' translate.tsv)" >> "$GITHUB_OUTPUT"
          echo "COMMIT_USERNAME=$(git log -1 --pretty=format:'%an' translate.tsv)" >> "$GITHUB_OUTPUT"
      - name: Run GitHub File Sync
        if: github.repository_owner == 'CuteReimu'
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          SKIP_PR: true
          GIT_EMAIL: ${{ steps.get-commit-info.outputs.COMMIT_EMAIL }}
          GIT_USERNAME: ${{ steps.get-commit-info.outputs.COMMIT_USERNAME }}
